apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: infra-user-cluster-dev
spec:
  instances: 3
  superuserSecret:
    name: pg-su-app-secret

  bootstrap:
    initdb:
      database: appuser
      owner: appuser
      secret:
        name: dev-app-secret
  storage:
    size: 4Gi

  monitoring:
    enablePodMonitor: true
