version: "3.9"
services:
  go-infra:
    image: ${DOCKER_REGISTRY-jtrahan88/}goinfra:${DOCKER_IMG_TAG-dev}
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ovnet1
    volumes:
      - ${LE_VOL-/etc/letsencrypt}:/app/.certbot/config
    secrets:
      - cf_token.ini
      - do.vps.env
    ports:
      - "8993:8993"
    entrypoint: "/app/server --envfile /run/secrets/do.vps.env"
networks:
  ovnet1:
    external: true
    name: ovnet1
secrets:
  cf_token.ini:
    external: true
  do.vps.env:
    external: true
