version: '3.9'
services:
  postgres:
    user: "${PG_UID-1002}:${PG_GID-1003}"
    image: postgres:14-alpine
    ports:
      - ${DB_PORT-5432}:5432
    volumes:
      - ${DB_PATH-/etc/goinfra/postgres}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_USER=${DB_USER-goinfra}
      - POSTGRES_DB=-${DB_NAME-goinfra_db}
    networks:
      - ovnet3
networks:
  ovnet3:
    external: true
    