version: "3.8"
services:
  go-infra:
    image: git.trahan.dev/jtrahan/go-infra:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - ovnet1
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    secrets:
      - trahan.dev_token
      - trahan.dev_zoneid
      - DB_PW
      - cloudflare_dns_api
    deploy:
      placement:
        constraints:
          - node.labels.dev01 == true
    ports:
      - "8993:8993"
    user: root
networks:
  ovnet1:
    external: true
    name: ovnet1
secrets:
  trahan.dev_token:
    external: true
  trahan.dev_zoneid:
    external: true
  DB_PW:
    external: true
  cloudflare_dns_api:
    external: true
