version: "3.9"
services:
  go-infra:
    image: ${DOCKER_REGISTRY-jtrahan88/}goinfra:${DOCKER_IMG_TAG-dev}
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ovnet1
    #volumes:
      #- ${LE_VOL-/mnt/share/gluster/goinfra}:/app/.certbot/config
    secrets:
      - cf_token.ini
      - Docker.env
    ports:
      - "8993:8993"
    entrypoint: "/app/server --envfile /run/secrets/Docker.env"
    user: appuser
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.goinfra == true
networks:
  ovnet1:
    external: true
    name: ovnet1
secrets:
  cf_token.ini:
    external: true
  Docker.env:
    external: true
