version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_USER=${DB_USER-goinfra}
      - POSTGRES_DB=goinfra_db
    networks:
      - ovnet3
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
networks:
  ovnet3:
    external: true
    