version: "3.8"
services:
  go-infra:
    image: jtrahan88/goinfra:${DOCKER_IMG_TAG-dev}
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ovnet1
    volumes:
      - ${LE_VOL-/mnt/share/gluster/letsencrypt}:/etc/letsencrypt
      #- ./Docker.env:/app/.env
    secrets:
      - cf_token.ini
      - swarm.env
    ports:
      - "8993:8993"
    env_file:
      - /run/secrets/swarm.env
networks:
  ovnet1:
    external: true
    name: ovnet1
secrets:
  cf_token.ini:
    external: true
  swarm.env:
    external: true
