consumes:
    - application/json
definitions:
    UserLoginRequest:
        properties:
            password:
                type: string
                x-go-name: Password
            username:
                type: string
                x-go-name: UserName
        type: object
        x-go-package: github.com/babbage88/go-infra/webapi/authapi
host: localhost:8993
info:
    contact:
        email: test@trahan.dev
        name: Justin Trahan
    license:
        name: N/A
    termsOfService: there are no TOS at this moment, use at your own risk we take no responsibility
    title: go-infra API.
    version: v1.0.6
paths:
    /login:
        post:
            operationId: idOfloginEndpoint
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/UserLoginRequest'
                  x-go-name: Body
            responses:
                "200":
                    $ref: '#/responses/AuthToken'
            summary: Login a user and return token.
            tags:
                - login-tag
produces:
    - application/json
schemes:
    - http
    - https
swagger: "2.0"
