definitions:
    LoginResult:
        properties:
            enabled:
                type: boolean
                x-go-name: UserEnabled
            error:
                type: string
                x-go-name: Error
            password_valid:
                type: boolean
                x-go-name: PasswordValid
            success:
                type: boolean
                x-go-name: Success
            username_matches:
                type: boolean
                x-go-name: UserNameMatches
        type: object
        x-go-package: github.com/babbage88/go-infra/webapi/authapi
    UserDao:
        properties:
            created_at:
                x-go-name: CreatedAt
            email:
                type: string
                x-go-name: Email
            enabled:
                type: boolean
                x-go-name: Enabled
            id:
                format: int32
                type: integer
                x-go-name: Id
            is_deleted:
                type: boolean
                x-go-name: IsDeleted
            last_modified:
                x-go-name: LastModified
            role:
                type: string
                x-go-name: Role
            username:
                type: string
                x-go-name: UserName
        type: object
        x-go-package: github.com/babbage88/go-infra/services
info: {}
paths:
    /login:
        post:
            operationId: idOfloginEndpoint
            parameters:
                - in: body
                  name: userName
                  schema:
                    type: string
                  x-go-name: UserName
                - in: body
                  name: password
                  schema:
                    type: string
                  x-go-name: Password
                - in: body
                  name: isHashed
                  schema:
                    type: boolean
                  x-go-name: IsHashed
            responses:
                "200":
                    $ref: '#/responses/UserLoginResponse'
            summary: Login a user and return token.
            tags:
                - login-tag
responses:
    UserLoginResponse:
        description: Respose will return login result and the user info.
        schema:
            $ref: '#/definitions/UserDao'
swagger: "2.0"
