definitions:
  cloudflaredns.DnsRecordReq:
    properties:
      content:
        type: string
      name:
        type: string
      proxied:
        type: bool
      type:
        type: string
      comment:
        type: string
      ttl:
        type: number
      id:
        type: string
      zone_id:
        type: string
      zone_name:
        type: string
      last_modified:
        type: string
    type: object
basePath: /
host: localhost:8993
info:
  contact:
    email: support@swagger.io
    name: Justin
    url: trahan@babbage88
  description: Automation for hybrid web app deployments
  title: go-infra api
  version: "1.0"
paths: 
  /api/getalldns:
    get: 
      description: returns all DNS records in databasr
      operationId: GetAllDnsRecords
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cloudflaredns.DnsRecordReq'
swagger: "2.0"
