apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-infra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-infra
  template:
    metadata:
      labels:
        app: go-infra
    spec:
      containers:
        - name: go-infra
          image: ghcr.io/babbage88/go-infra:v1.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8993
            - containerPort: 8090
          command: ["/app/server"]
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: JWT_KEY
            - name: EXPIRATION_MINUTES
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: EXPIRATION_MINUTES
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: DATABASE_URL
            - name: JWT_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: JWT_ALGORITHM
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: DB_NAME
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: S3_ENDPOINT
            - name: S3_KEYID
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: S3_KEYID
            - name: S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: S3_SECRET
            - name: S3_DEFAULT_BUCKET
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: S3_DEFAULT_BUCKET
            - name: S3_USESSL
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: S3_USESSL
            - name: CLOUDFLARE_DNS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: CLOUDFLARE_DNS_API_TOKEN
            - name: USER_SEC_KEY
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: USER_SEC_KEY
            - name: WEBSOCKET_BASE
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: WEBSOCKET_BASE
            - name: VALKEY_ADDR
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: VALKEY_ADDR
            - name: VALKEY_USER
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: VALKEY_USER
            - name: VALKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: VALKEY_PASSWORD
            - name: SSH_SESSION_STORE_TYPE
              valueFrom:
                secretKeyRef:
                  name: goinfra-app-secrets
                  key: SSH_SESSION_STORE_TYPE
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "256Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: ghcr
