apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: infra-db
spec:
  backup:
    barmanObjectStore:
      destinationPath: s3://postgres-backups/devjtcom_infradb_bakups
      endpointURL: https://minio.trahan.dev
      s3Credentials:
        accessKeyId:
          name: cnpg-minio-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-minio-creds
          key: ACCESS_SECRET_KEY
  instances: 1
  bootstrap:
    initdb:
      database: infradb
      owner: infradbuser
      secret:
        name: infra-db-user
  storage:
    size: 7Gi
  postgresql:
    pg_hba:
      - host all all all scram-sha-256
  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: infradb-bakups
spec:
  schedule: "0 0 0 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: infra-db
