---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/ip-allocated-from-pool: node-pool
  name: infra-db-rw-svc
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  selector:
    cnpg.io/cluster: infra-db
    role: primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
